# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heyreach < Formula
  desc "CLI for HeyReach LinkedIn outreach automation"
  homepage "https://heyreach.io"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyreach/heyreach-cli-releases/releases/download/v1.0.1/heyreach_darwin_amd64.tar.gz"
      sha256 "8c16ab97437568ae69d33804c616ca9f20efea06c0a85e44b62fd099a7b98594"

      define_method(:install) do
        bin.install "heyreach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyreach/heyreach-cli-releases/releases/download/v1.0.1/heyreach_darwin_arm64.tar.gz"
      sha256 "d9bcba0b9f05d1663de26a2e88989efbeed2f9202c3c5a3e5e34111d011d701f"

      define_method(:install) do
        bin.install "heyreach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyreach/heyreach-cli-releases/releases/download/v1.0.1/heyreach_linux_amd64.tar.gz"
      sha256 "7c45b80c0abd2b10ade05a9e05590c4c9afe76a00dca21f6911f5f841d2ee0be"
      define_method(:install) do
        bin.install "heyreach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heyreach/heyreach-cli-releases/releases/download/v1.0.1/heyreach_linux_arm64.tar.gz"
      sha256 "e11c126de3a5c1055c2039fe603db8018b8419f344eda49ecada0b512fefbdd5"
      define_method(:install) do
        bin.install "heyreach"
      end
    end
  end

  test do
    system "#{bin}/heyreach version"
  end
end
